application: hd-events-hrd
version: 2
api_version: 1
runtime: python27
threadsafe: true

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /remote_api
  script: google.appengine.ext.remote_api.handler.app
  login: admin
- url: /expire
  login: admin
  script: main.app
- url: /expiring
  login: admin
  script: main.app
- url: /cronbugowners
  login: admin
  script: main.app
- url: /test.*
  login: admin
  script: gaeunit.app
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.handler.app
  login: admin
- url: /_km/.*
  script: keymaster.app
  login: admin
- url: /api/v1/.*
  script: api.app
  secure: optional
- url: .*
  script: main.app
  secure: always

libraries:
- name: django
  version: latest
- name: jinja2
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
